version: '3.7'

services:
  apache:
    image: httpd:2.4
    init: true
    hostname: apache
    network_mode: "host"

    volumes:
    - $PWD/htdocs:/usr/local/apache2/htdocs/ 
    - $PWD/apache-conf/other/:/usr/local/apache2/conf/other/
    - $PWD/apache-conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    - $PWD/apache-conf/extra/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
    - $PWD/ssl/server.crt:/usr/local/apache2/conf/server.crt
    - $PWD/ssl/server.key:/usr/local/apache2/conf/server.key
    - $PWD/ssl/caint.crt:/usr/local/apache2/conf/server-ca.crt
    
    environment:
    - TZ=JST-9

