version: '3.7'

services:
  nginx:
    image: nginx
    init: true
    hostname: nginx
    network_mode: "host"

    volumes:
    - $PWD/htdocs/:/usr/share/nginx/html/:ro 
    - $PWD/nginx-conf/ssl.conf:/etc/nginx/conf.d/ssl.conf:ro
    - $PWD/ssl/all.crt:/etc/nginx/server.crt
    - $PWD/ssl/server.key:/etc/nginx/server.key
    # when self-signed
    #- $PWD/ssl/self-server.crt:/etc/nginx/server.crt
    #- $PWD/ssl/self-server.key:/etc/nginx/server.key
    
    environment:
    - TZ=JST-9

